### ISSUE TITLE
Git push failed for SNAP model

### ISSUE THREAD

**Issue by kkt-nrc** [NRC-Research/SNAP-issues#8] opened 2021-07-07 18:22 UTC
when trying to push a snap model using the Model Editor, failure noted
![Git push failed](https://user-images.githubusercontent.com/85764705/124809804-89e66700-df2e-11eb-81ab-2382b21e4f50.PNG)
[Git_failed_me.screen.txt](https://github.com/NRC-Research/SNAP-issues/files/6779323/Git_failed_me.screen.txt)

**Comment by NRCgg** [comment] 2021-07-13 19:08
> Does saving, closing, and re-opening the model fix the issue? What exactly occurred to lead to this state?

This didn't solve the issue.

I have some more information using SNAP 3.1.7 with Git plugin 2.0.2

- Condition:  In RHEL environment I cloned from our Arthur-TRACE-models  repo  using:

> git clone https://github.com/NRC-Research/Arthur-TRACE-models.git

- Then I started the Model Editor application and loaded a SNAP model from the Arthur-TRACE-models directory.
- I made a change to the model and then saved it, added it, and committed it.  This all seemed to go fine.
- When I went to "push" the model to the origin, I got:

![image](https://user-images.githubusercontent.com/56318952/125510629-49b3cdae-6c2b-4289-bf72-0dba2b878edd.png)

- Then, out of curiosity, I tried to "pull" from the same origin, I got:

![image](https://user-images.githubusercontent.com/56318952/125510778-e17b1086-bf89-4007-8be0-1fd05ef0ca2b.png)

**Comment by kroc-apt** [comment] 2021-08-12 21:13
After reviewing the described issue we have determined that the problem stems from an incorrect authentication configuration. More specifically, it appears that a personal access token was either not defined, or was defined without the required NRC organization approval. The following steps will guide you through the process of getting the authentication mechanism configured as required:

1.	Create a Personal Access Token (be aware that this token will expire at a time specified during creation) – This token can easily be created using steps outlined in the following link: https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token

2.	Provide NRC Organization Access to the Personal Access Token – The token created by the previous step must next be registered with the NRC organization authentication mechanism. The steps to do this are outlined in the following link: 

https://docs.github.com/en/github/authenticating-to-github/authenticating-with-saml-single-sign-on/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on

3.	Clone the Repository using the Authorized Personal Access Token – The repository should be cloned using the following commands:
Using GIT Bash commandline enter the following (or whatever GIT engine available):  

git clone https://<USERNAME>:<PERSONAL_AUTHENTICATION_TOKEN>@github.com/<PATH_TO_REPO>.git
(i.e. https://kroc-apt:ab7zedfh716@github.com/NRC-Research/Arthur-TRACE-models.git)   
       
4.	Open the model with the Model Editor – Open an med file from within the cloned directory.
5.	Push and Pull - SNAP will now provide the ability to push and pull as desired.

Using these instructions we were able to successfully pull from the repository. The push operation gave us a permission error, but it is suspected that this is intended behavior (we do not have permission to write to the specified repository). We have also successfully tested this process using a sample test github repository. All of this was tested using SNAP 3.1.8 and version 2.0.2 of the GIT plug-in.

Hope this helps!

**Comment by NRCgg** [comment] 2021-08-14 15:33
I tried the above process (created PAT, checked out from command line using PAT as indicated above), created a branch and made some changes in SNAP - trying to push gives me:

![image](https://user-images.githubusercontent.com/56318952/129451375-a2c2dda7-9686-4f91-abc2-e2e9fcffb657.png)

**Comment by kroc-apt** [comment] 2021-08-17 15:08
Did you stage and commit before pushing?

**Comment by NRCgg** [comment] 2021-08-18 12:21
I can get all the windows versions (RESGC and NRC laptop) to push IF I configure git to NOT check SSL verification.  That is, while in the checked out model directory:

git config --local http.sslVerify false

The differences I mentioned previously where evidently caused by having the http.sslVerify set in the global config for my account.  I don't know why there is an SSL issue though, I imported the cert for github.com.  I am not sure I have the SSL stuff figured out though so maybe I am not pointing to the right cert.crt file or using openssl.

The issue with the RHEL version noted above seems to be related to selecting to push to "all remotes".  After disabling SSL, if I try to push to the one origin listed then I get this error:

![image](https://user-images.githubusercontent.com/56318952/129896871-271e2729-30f3-40c2-b827-a2a3ffb6ddf8.png)

ie: the "git-receive-pack" issue

**Closed** 2021-09-22 19:41 UTC
Labels: bug, SNAP-GIT
